-- Payslip system: employee payroll fields + weekly payslip records

-- Add payroll fields to users (employees)
ALTER TABLE users ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS bsb VARCHAR(10);
ALTER TABLE users ADD COLUMN IF NOT EXISTS account_number VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS annual_salary NUMERIC(10,2) DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS super_fund_name VARCHAR(200) DEFAULT 'SGC - CareSuper';
ALTER TABLE users ADD COLUMN IF NOT EXISTS super_fund_usi VARCHAR(50) DEFAULT '400051382';
ALTER TABLE users ADD COLUMN IF NOT EXISTS tax_rate NUMERIC(5,4) DEFAULT 0.0853;

-- Weekly payslips generated by payroll manager
CREATE TABLE IF NOT EXISTS payslips (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  employee_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  store_id UUID NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  week_start DATE NOT NULL,
  week_end DATE NOT NULL,
  payment_date DATE NOT NULL,

  -- Hours and earnings
  ordinary_hours NUMERIC(6,2) NOT NULL DEFAULT 0,
  hourly_rate NUMERIC(8,4) NOT NULL DEFAULT 0,
  gross_pay NUMERIC(10,2) NOT NULL DEFAULT 0,

  -- Tax (PAYG) — editable by payroll
  tax_amount NUMERIC(10,2) NOT NULL DEFAULT 0,

  -- Superannuation (11.5% of gross by default, editable)
  super_rate NUMERIC(5,4) NOT NULL DEFAULT 0.115,
  super_amount NUMERIC(10,2) NOT NULL DEFAULT 0,

  -- Net pay = gross - tax
  net_pay NUMERIC(10,2) NOT NULL DEFAULT 0,

  -- YTD figures (snapshot at time of generation)
  ytd_gross NUMERIC(12,2) NOT NULL DEFAULT 0,
  ytd_tax NUMERIC(12,2) NOT NULL DEFAULT 0,
  ytd_super NUMERIC(12,2) NOT NULL DEFAULT 0,

  -- Status
  status VARCHAR(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'sent')),
  sent_at TIMESTAMP,
  generated_by UUID REFERENCES users(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT unique_payslip_per_employee_week UNIQUE (employee_id, week_start)
);

CREATE INDEX IF NOT EXISTS idx_payslip_employee ON payslips(employee_id);
CREATE INDEX IF NOT EXISTS idx_payslip_week ON payslips(week_start);
CREATE INDEX IF NOT EXISTS idx_payslip_store ON payslips(store_id);
CREATE INDEX IF NOT EXISTS idx_payslip_status ON payslips(status);

-- Seed random addresses and bank details for existing employees
UPDATE users SET
  address = CASE
    WHEN id = (SELECT id FROM users WHERE role = 'employee' LIMIT 1 OFFSET 0) THEN '1569 Heatherton Rd, Dandenong North VIC 3175'
    WHEN id = (SELECT id FROM users WHERE role = 'employee' LIMIT 1 OFFSET 1) THEN '42 Chapel St, Windsor VIC 3181'
    WHEN id = (SELECT id FROM users WHERE role = 'employee' LIMIT 1 OFFSET 2) THEN '15 Station Rd, Cheltenham VIC 3192'
    ELSE floor(random() * 200 + 1)::text || ' Example St, Melbourne VIC 3000'
  END,
  bsb = '063-244' || floor(random() * 9)::text,
  account_number = floor(random() * 90000000 + 10000000)::text,
  annual_salary = COALESCE(hourly_wage, 25) * 38 * 52
WHERE role = 'employee' AND address IS NULL;
